name: flutter_application_1
description: "A fitness and gym management application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.4
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.19.1
  intl: ^0.20.2
  rive: ^0.13.20
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  signalr_netcore: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mock/
    - assets/images/motivationpic.png
    - assets/images/8904-17031-weightlifting-competition.riv
